//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPLBK.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Orders
    {
        public int id { get; set; }
        public int id_user { get; set; }
        public int id_layanan { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        [DataType(DataType.Date)]
        public System.DateTime tanggalpemesanan { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        [DataType(DataType.Date)]
        public System.DateTime tanggaldipesan { get; set; }
        public int biaya { get; set; }
        public string status { get; set; }
        public string kode { get; set; }
        public int jumlah { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual Users Users { get; set; }


    }
}
